name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    needs: [pre-commit]
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run tox targets for ${{ matrix.python-version }}
        run: uvx --with tox-uv tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

  release:
    needs: [pre-commit, tests]
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    environment: release

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Build
        run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
